const GAME = {
  title: 'Krvavý grimoár a Sedm pečetí',
  intro: `Kutná Hora se otřásá v základech. Zmizel Liber Peccatorum Montanorum — Krvavý grimoár, temná kronika hříchů města. Sedm pečetí vede po stopách těch, kteří měli důvod knihu ukrást.`,
  startNote: `Šest skupin vyrazí městem. Nejprve však získají první indicii. Pak je čeká sedm pečetí. Ruthardtka zůstává mimo mapu — lapka, který nepozná únikovou cestu, dlouho lapkou nezůstane.`,
  firstClue: {
    icon:'✦',
    nav:'Čísla. Písmena. První stopa.',
    title:'PRIMA VESTIGIA',
    sub:'První stopa před cestou městem.',
    text:`Ještě než se vydáte za sedmi pečetěmi, dostanete jedinou stopu navíc. Zapište si její výsledek. Budete ho potřebovat až na konci.`,
    cipher:'21 – I',
    hint:'Čísla čtěte jako písmena.',
    note:`Až si budete jisti, že jste stopu rozluštili a zapsali, označte ji jako získanou. Aplikace ji zatím nekontroluje.`
  },
  stages: [
    {
      id:'monks', icon:'✠', internal:'Řádoví bratři',
      latin:'ORDO, LAPIS ET PECCATUM', sub:'Řád. Kázeň. Kříže. Kámen. Sochy.',
      gps:{lat:49.94630, lon:15.26370, radius:90},
      location:'Jezuitská kolej – galerie soch',
      locationText:`Stojíte čelem k chrámu na cestě, po níž po generace táhli kněží, kazatelé, hříšníci, pokrytci a lidé, kteří byli přesvědčeni, že hříšníci jsou vždy ti druzí.`,
      legend:`Přes den se káže o hříchu. V noci se hřích pečlivě zkoumá v praxi. Lidé zapomínají slova. Ale znamení si pamatují.`,
      task:`Najděte mezi kamennými světci pět znamení: LEBKA, VĚDRO S VODOU, LEV, RÝČ, VĚŽ. Seřaďte je v pořadí, v jakém je potkáte.`,
      answerHash:'55d89e3da9e35f7bd74ddbb8204b5da59f40f2d8d298bf2c74ede1f819883b96',
      answerLabel:'Zadejte pořadí pěti znamení bez mezer (např. VEZ-RYC-LEV-...)',
      hint:`Nehledejte jména. Dívejte se na to, co sochy drží v rukou nebo mají u nohou.`,
      success:`Správně. Kamenní svatí promluvili. Ne slovy. Znameními. Věž. Rýč. Lev. Vědro s vodou. Lebka.`,
      literature:`Kdyby zdejší řádoví bratři začali jeden po druhém umírat jako v románu Jméno růže Umberta Eca, Vilém z Baskervillu by věděl, kde začít: u stop, symbolů a obrazů.`,
      seal:'T2'
    },
    {
      id:'bells', icon:'🔔', internal:'Zvoníci',
      latin:'VOX CAMPANAE, VOX MORTIS', sub:'Hlas zvonu. Hlas smrti.',
      gps:{lat:49.94830, lon:15.26760, radius:90},
      location:'Chrám sv. Jakuba',
      locationText:`Věž, která bdí nad městem, slyšela radost i poplach, svatby i smrt.`,
      legend:`Zvon nevypráví. Jen svolává. O zbytek se postarají lidé — a ti mají paměť podstatně horší.`,
      task:`V básni Jiřího Ortena „Svatý Jakub“ určete správné pořadí motivů: milenci – havíři – zbloudilí – mrtví. Výsledkem je čtyřmístný kód.`,
      answerHash:'bcf1b6a7a986e20e0ff021f9127b89b84d3ac8b62de745a59cf905afffe36997',
      answerLabel:'Zadejte čtyřmístný kód',
      hint:`Každému ze čtyř motivů přiřaďte pořadí, v jakém v básni zazní.`,
      success:`Správně. Zvon promluvil tak, jak umí nejlépe — pořadím hlasů, které svolává.`,
      literature:`Ortenův Svatý Jakub připomíná, že město lze číst i sluchem: zvon nese paměť dál, i když lidé už dávno mlčí.`,
      seal:'?'
    },
    {
      id:'miners', icon:'⚒', internal:'Havíři',
      latin:'ARGENTUM, TENEBRAE ET LABYRINTHUS', sub:'Stříbro. Temnota. Bludiště.',
      gps:{lat:49.94750, lon:15.26540, radius:90},
      location:'Hrádek – České muzeum stříbra',
      locationText:`Veškeré bohatství Kutné Hory začínalo ve tmě.`,
      legend:`Staří havíři prý říkali, že v Kutné Hoře se bohatne dvěma způsoby: nahoře podvodem, dole potem. A občas také obojím.`,
      task:`Najděte cestu od štoly sv. Jiří k havíři. Po cestě si zapisujte písmena, která skutečně minete. Písmena ze slepých chodeb se nepočítají.`,
      image:'assets/dulni_bludiste.png',
      answerHash:'dc03700418b911c2587f38fe391f1fe7ba3b49e659554fe55cf52c4cb80f40f8',
      answerLabel:'Zadejte slovo z bludiště',
      hint:`Nečtěte všechna písmena. Jen ta na jediné správné cestě k havíři.`,
      success:`Správně. Temnota vás nepohltila. Prošli jste tam, kde by jiní zabloudili.`,
      literature:`Kdyby tudy procházel profesor Lidenbrock z Verneovy Cesty do středu Země, nejspíš by měl radost. I on věděl, že podzemí nepustí dál toho, kdo se dívá nepozorně.`,
      seal:'?'
    },
    {
      id:'alchemists', icon:'⚗', internal:'Alchymisté',
      latin:'IGNIS FALSA ET VANA SCIENTIA', sub:'Oheň. Tajemství. Marné vědění.',
      gps:{lat:49.94981, lon:15.26881, radius:80},
      location:'Sankturinovský dům',
      locationText:`Dům s věží na náměstí, kde se mísila věda, alchymie a vůně tiskařské černě.`,
      legend:`Po zmizení grimoáru zůstala rozbitá retorta a obraz, do něhož je třeba dívat se jinak než obyčejně.`,
      task:`Rozluštěte stereogram a získejte slovo ARCANUM. Pak použijte alchymistická čísla 3, 4 a 7.`,
      answerHash:'9b7b5ee474dbaac2ce8ddcfaf07ae2a938fe3976bdea082a3868b2be5bc37fa5',
      answerLabel:'Zadejte třípísmenný výsledek',
      hint:`Pokud stereogram vzdoruje, hledejte Arcanum divinae sapientiae. Pak vezměte 3., 4. a 7. písmeno slova ARCANUM.`,
      success:`Bravo — ARCANUM. Tajemství. Skrytá věc. Poznání určené jen těm, kteří vědí, jak se dívat.`,
      literature:`Dan Brown ve svém pražském románu Tajemství všech tajemství znovu pracuje s městem jako labyrintem skrytého vědění.`,
      seal:'U1',
      assetNote:'SEM VLOŽIT STEREOGRAM'
    },
    {
      id:'councillors', icon:'⚖', internal:'Konšelé',
      latin:'PECUNIA, LEX ET MENDACIUM', sub:'Peníze. Zákon. Lež.',
      gps:{lat:49.95000, lon:15.26528, radius:80},
      location:'Kamenný dům',
      locationText:`Takové domy nestavěli lidé, kteří chtěli zůstat nenápadní.`,
      legend:`Pět mužů. Pět funkcí. Pět podezřelých částek. Každý tvrdí, že je poctivý. Každý se při výslechu potí.`,
      taskHtml:`<ol class="list"><li>Správce městské pokladny si odnesl o 100 grošů více než purkmistr.</li><li>Purkmistr si odnesl o 100 grošů více než rychtář.</li><li>Výběrčí cla získal přesně dvojnásobek toho, co městský písař.</li><li>Matěj si odnesl méně než Smil, ale více než Vaněk.</li><li>Beneš si přišel na větší částku než Mikuláš.</li><li>Mikuláš nebyl rychtář.</li><li>Smil nebyl ani purkmistr, ani správce městské pokladny.</li></ol><p><strong>Kdo ukradl nejvyšší částku?</strong></p>`,
      answerHash:'56ed32166f19ccbca96a04619369db7c7b8f3587fd946d7dbf64095b932882b2',
      answerLabel:'Zadejte jméno největšího viníka',
      hint:`Začněte funkcemi a částkami, teprve potom přiřazujte jména. Řetězec je rychtář → purkmistr → správce pokladny, vždy +100.`,
      success:`Správně. Městské účty konečně přestaly lhát. Beneš seděl nejblíž truhle s penězi.`,
      literature:`Kdyby se mezi konšely objevil Josef K. z Kafkova Procesu, možná by se tu cítil jako doma. Vy jste měli výhodu: dostali jste indicie.`,
      seal:'?'
    },
    {
      id:'mint', icon:'◉', internal:'Mincíři',
      latin:'ARGENTUM, MONETA ET FRAUS', sub:'Stříbro. Mince. Podvod.',
      gps:{lat:49.94833, lon:15.26861, radius:80},
      location:'Vlašský dvůr',
      locationText:`Kde jsou peníze, tam se dříve či později objeví někdo s geniálním nápadem dát do směsi méně stříbra.`,
      legend:`Stříbro nelže. Váha také ne. Zato mincíři… ti občas ano.`,
      taskHtml:`<div class="rulebox"><strong>Pravidlo:</strong> Příměs smí tvořit přesně jednu desetinu celé směsi.</div><table style="width:100%;border-collapse:collapse"><tr><th>Várka</th><th>Stříbro</th><th>Příměs</th></tr><tr><td>A</td><td>45</td><td>5</td></tr><tr><td>B</td><td>72</td><td>8</td></tr><tr><td>C</td><td>63</td><td>7</td></tr><tr><td>D</td><td>54</td><td>9</td></tr><tr><td>E</td><td>81</td><td>9</td></tr></table><p><strong>Která várka porušuje pravidlo?</strong></p>`,
      answerHash:'3f39d5c348e5b79d06e842c114e6cc571583bbf44e4b0ebfda1a01ec05745d43',
      answerLabel:'Zadejte písmeno várky',
      hint:`Sečtěte stříbro a příměs. Pak ověřte, zda příměs tvoří 1/10 výsledku.`,
      success:`Správně. Várka D je ošizená. Někdo doufal, že jeho čísla nikdo nepřepočítá.`,
      literature:`Peníze mají v literatuře zvláštní vlastnost: čím víc jich postava chce, tím méně rozumně se obvykle chová. Balzac o tom věděl své.`,
      seal:'?'
    },
    {
      id:'robbers', icon:'☠', internal:'Lapkové',
      latin:'UMBRA, FURTUM ET FUGA', sub:'Stín. Krádež. Útěk.',
      gps:null,
      location:'Ruthardtka – tajné místo mimo mapu',
      locationText:`Žádný název. Žádná mapa. Žádná šipka. Lapka, který nepozná dobrou únikovou cestu, dlouho lapkou nezůstane.`,
      legend:`V noci, kdy zmizel Krvavý grimoár, zahlédl jeden z vašich lidí muže s balíkem pod pláštěm. Běžel. Za ním dva strážní. Před ním úzká ulice mezi vysokými zdmi. Pak zmizel. Zanechal jen obraz.`,
      task:`Najděte místo z fotografie. Porovnávejte domy, zdi, zatáčky, okna a střechy. Ověření na místě doplníme těsně před hrou podle skutečného stavu.`,
      answerHash:null,
      answerLabel:'Ověření lapků doplnit před hrou',
      hint:`Když budete úplně v koncích, můžete se poptat místních pacholků. Jen jim nevykládejte proč.`,
      success:`Ruthardka. Místo, kde není radno příliš se opírat o zdi. Ozvěna tu občas nese jméno: Róza… za… za…`,
      literature:`Kdo se někdy potkal s Jindřichem ze Skalice, ví, že jméno Róza nepatří jen květině. A klidně by se tudy mohl plížit François Villon — básník, rváč a zlodějíček.`,
      seal:'6U'
    }
  ]
};
